#!/bin/sh

export PATH="$PATH:/opt/homebrew/bin"
if which mint > /dev/null; then
  unset SDKROOT
  cd ..
  MOCKOLO="mint run mockolo"
else
  echo "error: mint is not installed. Please install it via brew install mint and run mint bootstrap to install all dependencies."
  exit 0
fi

$MOCKOLO --version
$MOCKOLO -s Knowledge -s Common -s DeveloperOverlay -s Domain -s Networking -s PharmaDatabase -s RichTextRenderer -d Knowledge/Tests/UnitTests/AutogeneratedMocks.swift --exclude-imports ApolloAPI KnowledgeGraphQLEntities Segment --header  "@testable import Knowledge_DE;" || true
