
//
// DesignSystemColorTokens.swift
//

// Do not edit directly
// Generated on Tue, 23 Jul 2024 10:20:33 GMT


import UIKit

internal enum DesignSystemColorTokens {
    internal static let darkColorBackgroundAccent = UIColor(0xff1d6670)
    internal static let darkColorBackgroundAccentSubtle = UIColor(0xff262f36)
    internal static let darkColorBackgroundBackdrop = UIColor(0x99000000)
    internal static let darkColorBackgroundContrast = UIColor(0xffced1d6)
    internal static let darkColorBackgroundElevated = UIColor(0xff24282d)
    internal static let darkColorBackgroundError = UIColor(0xffa45355)
    internal static let darkColorBackgroundErrorSubtle = UIColor(0xff312b31)
    internal static let darkColorBackgroundInfo = UIColor(0xff2f538a)
    internal static let darkColorBackgroundInfoSubtle = UIColor(0xff282e39)
    internal static let darkColorBackgroundOnAccent = UIColor(0xffffffff)
    internal static let darkColorBackgroundPlaceholder = UIColor(0xff393e47)
    internal static let darkColorBackgroundPrimary = UIColor(0xff1a1c1c)
    internal static let darkColorBackgroundSecondary = UIColor(0xff1e2125)
    internal static let darkColorBackgroundSuccess = UIColor(0xff28816b)
    internal static let darkColorBackgroundSuccessSubtle = UIColor(0xff262e33)
    internal static let darkColorBackgroundTextHighlightCustomBlue = UIColor(0xff015e7d)
    internal static let darkColorBackgroundTextHighlightFind = UIColor(0x99b2ab39)
    internal static let darkColorBackgroundTextHighlightLearningRadar = UIColor(0xfff07575)
    internal static let darkColorBackgroundTextHighlightPrimary = UIColor(0x73b2ab39)
    internal static let darkColorBackgroundTextHighlightQbankKeyInfo = UIColor(0xffa4792d)
    internal static let darkColorBackgroundTextHighlightRelevancePrimary = UIColor(0xff233d3d)
    internal static let darkColorBackgroundTextHighlightRelevanceSecondary = UIColor(0xcc233d3d)
    internal static let darkColorBackgroundTextHighlightSecondary = UIColor(0xff494a2f)
    internal static let darkColorBackgroundTransparent = UIColor(0x00ffffff)
    internal static let darkColorBackgroundTransparentSelected = UIColor(0xff40454f)
    internal static let darkColorBackgroundWarning = UIColor(0xffa4792d)
    internal static let darkColorBackgroundWarningSubtle = UIColor(0xff32302f)
    internal static let darkColorBorderAccent = UIColor(0xff2e9aa7)
    internal static let darkColorBorderAccentSubtle = UIColor(0xff1d6670)
    internal static let darkColorBorderError = UIColor(0xffd07c7c)
    internal static let darkColorBorderOnAccent = UIColor(0xffffffff)
    internal static let darkColorBorderPrimary = UIColor(0xff5b5f67)
    internal static let darkColorBorderSecondary = UIColor(0x4d93959f)
    internal static let darkColorBorderSuccess = UIColor(0xff41a48a)
    internal static let darkColorCanvas = UIColor(0xff111111)
    internal static let darkColorDividerPrimary = UIColor(0xff32363e)
    internal static let darkColorDividerSecondary = UIColor(0x2693959f)
    internal static let darkColorIconAccent = UIColor(0xff2e9aa7)
    internal static let darkColorIconBrand = UIColor(0xff2e9aa7)
    internal static let darkColorIconError = UIColor(0xffd07c7c)
    internal static let darkColorIconInfo = UIColor(0xff6e95cf)
    internal static let darkColorIconOnAccent = UIColor(0xffffffff)
    internal static let darkColorIconOnAccentSubtle = UIColor(0x99ffffff)
    internal static let darkColorIconPrimary = UIColor(0xffd8dade)
    internal static let darkColorIconQuaternary = UIColor(0xff757a84)
    internal static let darkColorIconSecondary = UIColor(0xffced1d6)
    internal static let darkColorIconSuccess = UIColor(0xff41a48a)
    internal static let darkColorIconTertiary = UIColor(0xff93979f)
    internal static let darkColorIconWarning = UIColor(0xffcbac76)
    internal static let darkColorTextAccent = UIColor(0xff2e9aa7)
    internal static let darkColorTextDottedUnderline = UIColor(0xff93979f)
    internal static let darkColorTextError = UIColor(0xfff49a9a)
    internal static let darkColorTextInfo = UIColor(0xff99c1fa)
    internal static let darkColorTextOnAccent = UIColor(0xffffffff)
    internal static let darkColorTextOnAccentSubtle = UIColor(0x99ffffff)
    internal static let darkColorTextPrimary = UIColor(0xffced1d6)
    internal static let darkColorTextQuaternary = UIColor(0xff757a84)
    internal static let darkColorTextSecondary = UIColor(0xffb9bcc3)
    internal static let darkColorTextSuccess = UIColor(0xffa6f2dd)
    internal static let darkColorTextTertiary = UIColor(0xff93979f)
    internal static let darkColorTextUnderline = UIColor(0xff757a84)
    internal static let darkColorTextWarning = UIColor(0xfffae0b3)
    internal static let lightColorBackgroundAccent = UIColor(0xff047a88)
    internal static let lightColorBackgroundAccentSubtle = UIColor(0xffe7f6f8)
    internal static let lightColorBackgroundBackdrop = UIColor(0x99000000)
    internal static let lightColorBackgroundContrast = UIColor(0xff314554)
    internal static let lightColorBackgroundElevated = UIColor(0xffffffff)
    internal static let lightColorBackgroundError = UIColor(0xffdc4847)
    internal static let lightColorBackgroundErrorSubtle = UIColor(0xfffde8e8)
    internal static let lightColorBackgroundInfo = UIColor(0xff295dae)
    internal static let lightColorBackgroundInfoSubtle = UIColor(0xffe7effe)
    internal static let lightColorBackgroundOnAccent = UIColor(0xffffffff)
    internal static let lightColorBackgroundPlaceholder = UIColor(0xffe0e6eb)
    internal static let lightColorBackgroundPrimary = UIColor(0xffffffff)
    internal static let lightColorBackgroundSecondary = UIColor(0xfff5f7f9)
    internal static let lightColorBackgroundSuccess = UIColor(0xff0b8363)
    internal static let lightColorBackgroundSuccessSubtle = UIColor(0xffe8f8f4)
    internal static let lightColorBackgroundTextHighlightCustomBlue = UIColor(0xff99e6ff)
    internal static let lightColorBackgroundTextHighlightFind = UIColor(0xfff6bc56)
    internal static let lightColorBackgroundTextHighlightLearningRadar = UIColor(0x4dee6160)
    internal static let lightColorBackgroundTextHighlightPrimary = UIColor(0xfff3eb75)
    internal static let lightColorBackgroundTextHighlightQbankKeyInfo = UIColor(0xffdf9411)
    internal static let lightColorBackgroundTextHighlightRelevancePrimary = UIColor(0xff8adcc6)
    internal static let lightColorBackgroundTextHighlightRelevanceSecondary = UIColor(0xffd0f1e8)
    internal static let lightColorBackgroundTextHighlightSecondary = UIColor(0xfffaf5b8)
    internal static let lightColorBackgroundTransparent = UIColor(0x00ffffff)
    internal static let lightColorBackgroundTransparentSelected = UIColor(0xff607585)
    internal static let lightColorBackgroundWarning = UIColor(0xffdf9411)
    internal static let lightColorBackgroundWarningSubtle = UIColor(0xfffef3e1)
    internal static let lightColorBorderAccent = UIColor(0xff047a88)
    internal static let lightColorBorderAccentSubtle = UIColor(0xff85d3dc)
    internal static let lightColorBorderError = UIColor(0xffdc4847)
    internal static let lightColorBorderOnAccent = UIColor(0xffffffff)
    internal static let lightColorBorderPrimary = UIColor(0xffa3b2bd)
    internal static let lightColorBorderSecondary = UIColor(0x4da3b2bd)
    internal static let lightColorBorderSuccess = UIColor(0xff0b8363)
    internal static let lightColorCanvas = UIColor(0xffeef2f5)
    internal static let lightColorDividerPrimary = UIColor(0xffe0e6eb)
    internal static let lightColorDividerSecondary = UIColor(0x4da3b2bd)
    internal static let lightColorIconAccent = UIColor(0xff047a88)
    internal static let lightColorIconBrand = UIColor(0xff0aa6b8)
    internal static let lightColorIconError = UIColor(0xffdc4847)
    internal static let lightColorIconInfo = UIColor(0xff295dae)
    internal static let lightColorIconOnAccent = UIColor(0xffffffff)
    internal static let lightColorIconOnAccentSubtle = UIColor(0x99ffffff)
    internal static let lightColorIconPrimary = UIColor(0xff1a1c1c)
    internal static let lightColorIconQuaternary = UIColor(0xffa3b2bd)
    internal static let lightColorIconSecondary = UIColor(0xff40515e)
    internal static let lightColorIconSuccess = UIColor(0xff0b8363)
    internal static let lightColorIconTertiary = UIColor(0xff607585)
    internal static let lightColorIconWarning = UIColor(0xffdf9411)
    internal static let lightColorTextAccent = UIColor(0xff047a88)
    internal static let lightColorTextDottedUnderline = UIColor(0xff607585)
    internal static let lightColorTextError = UIColor(0xffc02725)
    internal static let lightColorTextInfo = UIColor(0xff1c427d)
    internal static let lightColorTextOnAccent = UIColor(0xffffffff)
    internal static let lightColorTextOnAccentSubtle = UIColor(0x99ffffff)
    internal static let lightColorTextPrimary = UIColor(0xff1a1c1c)
    internal static let lightColorTextQuaternary = UIColor(0xffa3b2bd)
    internal static let lightColorTextSecondary = UIColor(0xff40515e)
    internal static let lightColorTextSuccess = UIColor(0xff0a5c45)
    internal static let lightColorTextTertiary = UIColor(0xff607585)
    internal static let lightColorTextUnderline = UIColor(0xffa3b2bd)
    internal static let lightColorTextWarning = UIColor(0xff314554)
}
